[phases.setup]
nixPkgs = ["nodejs", "google-chrome", "vulkan-loader", "libGL"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build --if-present"]

[start]
cmd = "node src/app.js"
